# Generated by Django 5.2.4 on 2025-10-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qtaker",
            name="current_score",
            field=models.IntegerField(default=0),
        ),
    ]
