# Generated by Django 5.2.4 on 2025-11-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0002_qtaker_current_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qtaker",
            name="skill",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("expert", "Expert"),
                ],
                default="beginner",
                max_length=100,
            ),
        ),
    ]
