# Generated by Django 5.2.4 on 2025-11-08 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0003_alter_qtaker_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="qtaker",
            name="date_taken",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Event Date and Time",
            ),
            preserve_default=False,
        ),
    ]
