# Generated by Django 5.2.4 on 2025-11-08 12:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0004_qtaker_date_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
