# Generated by Django 5.2.4 on 2025-11-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0005_alter_question_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="qtaker",
            name="current_question_set",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
