# Generated by Django 5.2.4 on 2025-11-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0006_qtaker_current_question_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="qtaker",
            name="next_question_set",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
