# Generated by Django 5.2.4 on 2026-01-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0007_qtaker_next_question_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("text", "Text Answer"), ("radio", "Single Choice(checkbox)")],
                default="radio",
                max_length=20,
            ),
        ),
    ]
