# Generated by Django 5.2.4 on 2026-01-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0008_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="qtaker",
            name="last_question_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
