# Generated by Django 5.2.4 on 2026-01-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0009_qtaker_last_question_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="qtaker",
            name="last_text_answer",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
    ]
