# Generated by Django 4.2.7 on 2026-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0010_qtaker_last_text_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qtaker",
            name="current_question_set",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="qtaker",
            name="next_question_set",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
